apiVersion: v1
kind: Service
metadata:
  name: mirror
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: mirror
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mirror1
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: mirror
  type: LoadBalancer